---
services:
  jellyfin:
    image: jellyfin/jellyfin:2025081805
    user: root
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - jellyfin-data:/config
      - /mnt/media:/media
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.docker.network=hlel"
      - "traefik.docker.lbswarm=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.tls=false"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    deploy:
      update_config:
        order: start-first
    networks:
      - hlel

  qbittorrent:
    image: linuxserver/qbittorrent:5.1.2
    ports:
      - "8081:8081"              # web UI
      - "6881:6881"              # torrent traffic TCP
      - "6881:6881/udp"          # torrent traffic UDP
    environment:
      - PUID=${UID}                # your local user ID
      - PGID=${GID}                # your local group ID
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8081
      - UMASK_SET=000            # sensible file perms
    volumes:
      - qbittorrent-data:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Series:/series
      - /mnt/media/Watch:/watch
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.docker.network=hlel"
      - "traefik.docker.lbswarm=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qb.${DOMAIN_NAME}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.routers.qbittorrent.tls=false"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"
    deploy:
      update_config:
        order: start-first
    networks:
      - hlel

volumes:
  jellyfin-data: {}
  qbittorrent-data: {}

networks:
  hlel:
    name: hlel
    external: true