---
services:
  jellyfin:
    image: jellyfin/jellyfin:2025112405
    user: root
    ports:
      - "8096:8096" # need for direct connection on TV
    environment:
      - PUID=${CUID}
      - PGID=${CGID}
      - TZ=${TIMEZONE}
      - LIBVA_DRIVER_NAME=iHD
    volumes:
      - /dev/dri:/dev/dri
      - jellyfin-data:/config
      - jellyfin-cache:/cache
      - /mnt/media:/media
    deploy:
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.tls=true"
        - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      update_config:
        order: start-first
    networks:
      - hlel

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1
    ports:
      - "8081:8081"              # web UI
      - "6881:6881"              # torrent traffic TCP
      - "6881:6881/udp"          # torrent traffic UDP
    environment:
      - PUID=${CUID}                # your local user ID
      - PGID=${CGID}                # your local group ID
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8081
      - UMASK=000            # sensible file perms
    volumes:
      - qbittorrent-data:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Series:/series
      - /mnt/media/Watch:/watch
    deploy:
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.qbittorrent.rule=Host(`qb.${DOMAIN_NAME}`)"
        - "traefik.http.routers.qbittorrent.entrypoints=websecure"
        - "traefik.http.routers.qbittorrent.tls=true"
        - "traefik.http.routers.qbittorrent.tls.certresolver=cloudflare"
        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"
      update_config:
        order: start-first
    networks:
      - hlel

volumes:
  jellyfin-data: {}
  jellyfin-cache: {}
  qbittorrent-data: {}

networks:
  hlel:
    name: hlel
    external: true