---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2
    ports:
      - "3001:3001"
    volumes:
      - uptime-data:/app/data
    environment:
      - TZ=${TIMEZONE}
      - UMASK=0022
    networks:
      - sln
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.role == secondary

volumes:
  uptime-data: {}

networks:
  sln:
    name: hlel
    external: true