
services:
  portainer-agent:
    image: portainer/agent:2.33.5   # or 'latest' if you prefer
    ports:
      - "9001:9001"
    environment:
      # Change this to something unique if you want to identify this cluster
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      # Optional: if you use swarm configs/secrets, keep them accessible
      - /:/host
    networks:
      - sln
    deploy:
      restart_policy:
        condition: any



networks:
  sln:
    name: sln
    external: true