services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - $BASE_DIR/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.echo.local`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.tls=false"
      - "traefik.http.services.portainer-utils.loadbalancer.server.port=9000"
    restart: always
    networks:
      - hlcl

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ='Europe/Bucharest'
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEB_PASS}
      - CLI_ARGS=--webservice-interface=any
    volumes:
      - $BASE_DIR/configs/duplicati:/config                      # Duplicati configs
      - $BASE_DIR/configs:/source/configs:ro
      - $BASE_DIR/data:/source/data:ro
      - $BASE_DIR/data/backups:/backups                          # Backup destination (local disk or mount)
    ports:
      - 8200:8200
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
    restart: always
    networks:
      - hlcl


  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.echo.local`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.routers.n8n.tls=false"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=Europe/Bucharest
    volumes:
      - $BASE_DIR/data/n8n:/home/node/.n8n
      - $BASE_DIR/data/n8n/local-files:/files
    networks:
      - hlcl

networks:
  hlcl:
    name: hlcl
    external: true