---
services:

  portainer:
    image: portainer/portainer-ce:2.38.0
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
        - "traefik.http.services.portainer-utils.loadbalancer.server.port=9000"
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel


  n8n:
    image: docker.n8n.io/n8nio/n8n:2.7.2
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - n8n-data:/home/node/.n8n
      - n8n-local-files:/files
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN_NAME}`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls=true"
        - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      placement:
        constraints:
          - node.labels.role == secondary
    networks:
      - hlel

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1
    environment:
      - TZ=Europe/Bucharest
      - HOMEPAGE_ALLOWED_HOSTS=home.${DOMAIN_NAME}
      - HOMEPAGE_VAR_BASE_DOMAIN=${DOMAIN_NAME}
      - HOMEPAGE_VAR_NAS_ADDR=${NAS_ADDR}
      - HOMEPAGE_VAR_EXT_DOMAIN_NAME=${EXT_DOMAIN_NAME}
    configs:
      - source: homepage_settings_yaml
        target: /app/config/settings.yaml
      - source: homepage_services_yaml
        target: /app/config/services.yaml
      - source: homepage_bookmarks_yaml
        target: /app/config/bookmarks.yaml
      - source: homepage_widgets_yaml
        target: /app/config/widgets.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Optional: persistent user assets (custom icons/backgrounds):
      - homepage-data:/app/config/user
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.homepage.rule=Host(`home.${DOMAIN_NAME}`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls=true"
        - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

  svc-router:
    image: traefik/whoami:v1.11.0
    networks:
      - hlel
    deploy:
      replicas: 1
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.nas-router.rule=Host(`nas.${DOMAIN_NAME}`)"
        - "traefik.http.routers.nas-router.entrypoints=websecure"
        - "traefik.http.routers.nas-router.tls=true"
        - "traefik.http.routers.nas-router.tls.certresolver=cloudflare"
        - "traefik.http.services.nas-router.loadbalancer.server.url=http://${NAS_ADDR}:8080"


configs:
  homepage_settings_yaml:
    external: true
  homepage_services_yaml:
    external: true
  homepage_bookmarks_yaml:
    external: true
  homepage_widgets_yaml:
    external: true

volumes:
    homepage-data:
      external: true
    portainer-data: {}
    n8n-data: {}
    n8n-local-files: {}

networks:
  hlel:
    name: hlel
    external: true