---
services:
  database:
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/immich_pg_password
      - POSTGRES_INITDB_ARGS="--data-checksums"
      # DB_STORAGE_TYPE: "HDD"   # uncomment if your DB disk is HDD
    secrets:
      - immich_pg_password
    volumes:
#      - /srv/dvls/immich/postgres:/var/lib/postgresql/data
      - /srv/dvls/immich/postgres_pg18:/var/lib/postgresql
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      placement:
        constraints:
          - node.labels.role == primary
    shm_size: "128M"
    networks:
      - hlel

  redis:
    image: docker.io/valkey/valkey:9-alpine
    volumes:
      - /srv/dvls/immich/valkey_data:/data
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3-openvino
    # For HW accel, use tags like :release-cuda / :release-openvino / :release-rocm / :release-armnn
    environment:
      - TZ=${TIMEZONE}
      - MACHINE_LEARNING_DEVICE_IDS=GPU
    volumes:
      - /srv/dvls/immich/model_cache:/cache
      - /dev/dri:/dev/dri
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

  immich-server:
    image: ghcr.io/immich-app/immich-server:v3.0.1
    environment:
      - TZ=${TIMEZONE}
      # DB (must match database service)
      - DB_HOSTNAME=database
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD_FILE=/run/secrets/immich_pg_password
      - DB_DATABASE_NAME=${POSTGRES_DB}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - CREDENTIALS_DIRECTORY=/run/secrets
    secrets:
      - immich_pg_password
    volumes:
      - /srv/dvls/immich/library:/data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas_Vlad:/mnt/external/nas_Vlad
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.immich.rule=Host(`immich.${DOMAIN_NAME}`)"
        - "traefik.http.routers.immich.entrypoints=websecure"
        - "traefik.http.routers.immich.tls=true"
        - "traefik.http.routers.immich.tls.certresolver=cloudflare"
        - "traefik.http.services.immich.loadbalancer.server.port=2283"
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

secrets:
  immich_pg_password:
    external: true

networks:
  hlel:
    name: hlel
    external: true

