---
services:
  backrest:
    image: garethgeorge/backrest:v1.10.1
    hostname: echo
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TIMEZONE}
    volumes:
      # Backrest internal state
      - backrest_data:/data
      - backrest_config:/config
      - backrest_cache:/cache
      - backrest_tmp:/tmp
      # Mount the SAME service volumes read-only so Backrest can back them up
      - immich_library:/data/immich_library:ro
      - nas_nfs_share:/data/nfsnas
      - /mnt/media:/data/vexthdd
    deploy:
      restart_policy:
        condition: on-failure
        delay: 300s          # wait 60s between restarts
        max_attempts: 5    # stop restarting after 10 tries
      update_config:
        order: start-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.backrest.rule=Host(`backrest.${DOMAIN_NAME}`)"
        - "traefik.http.routers.backrest.entrypoints=websecure"
        - "traefik.http.routers.backrest.tls=true"
        - "traefik.http.routers.backrest.tls.certresolver=cloudflare"
        - "traefik.http.services.backrest.loadbalancer.server.port=9898"
        # helpful for service discovery / ops
        - "com.backups.role=backrest"
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

  syncthing-src:
    image: lscr.io/linuxserver/syncthing:2.0.12
    ports:
      - "22000:22000/tcp"   # Sync TCP
      - "22000:22000/udp"   # Sync QUIC/UDP
      - "21027:21027/udp"   # Local discovery
    environment:
      - PUID=${CUID}
      - PGID=${CGID}
      - TZ=${TIMEZONE}
      - UMASK=002
      - GUI_ADDRESS=0.0.0.0:8384
    volumes:
      - syncthing_src_config:/config
      - immich_library:/data/immich_library
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      labels:
        - "portainer.io/managed=true"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.enable=true"
        - "traefik.swarm.network=hlel"
        - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN_NAME}`)"
        - "traefik.http.routers.syncthing.entrypoints=websecure"
        - "traefik.http.routers.syncthing.tls=true"
        - "traefik.http.routers.syncthing.tls.certresolver=cloudflare"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      placement:
        constraints:
          - node.labels.role == primary
    networks:
      - hlel

volumes:
  # Backrest internal state/cache/config
  backrest_data:
  backrest_config:
  backrest_cache:
  backrest_tmp:
  # Reuse the SAME volume names your services use.
  immich_library:
    external: true
  wireguard-data:
    external: true
  syncthing_src_config:
    external: true
  nas_nfs_share:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_ADDR},nfsvers=4,hard,timeo=25,retrans=2"
      device: ":/nfs-share"

networks:
  hlel:
    name: hlel
    external: true
