---

services:

  gh-runner:
    image: myoung34/github-runner:latest
    container_name: gh-runner-stacks
    restart: unless-stopped
    environment:
      - REPO_URL="https://github.com/${GH_ORG}/${GH_REPO}"
      - RUNNER_SCOPE="repo"
      - RUNNER_NAME="stacks-runner"
      - LABELS="self-hosted,linux,docker,stacks"
      - RUNNER_WORKDIR="/_work"
      - ACCESS_TOKEN="${GH_RUNNER_PAT}"
      - CONFIGURED_ACTIONS_RUNNER_FILES_DIR="/runner/data"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BASE_DIR/data/gh-runner:/runner/data
      - $BASE_DIR:$BASE_DIR
