---
services:

  gh-runner:
    image: myoung34/github-runner:latest
    environment:
      - REPO_URL=https://github.com/${GH_ORG}/${GH_REPO}
      - RUNNER_SCOPE=repo
      - RUNNER_NAME=stacks-runner
      - LABELS=self-hosted,linux,docker,stacks
      - RUNNER_WORKDIR=/_work
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - DISABLE_AUTOMATIC_DEREGISTRATION=true
      - CONFIGURED_ACTIONS_RUNNER_FILES_DIR=/runner/data
    volumes:
      - runner-data:/runner/data
      - /_work:/_work
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      placement:
        constraints:
          - node.labels.role == primary

volumes:
  runner-data: {}
