
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.7.124      # Add the IP address of the proxy server
    - 172.21.0.102      # Traefik's Docker network address, Ip taken from logs
  ip_ban_enabled: true
  login_attempts_threshold: 3
# Text to speech
tts:
  - platform: google_translate


influxdb:
  api_version: 2
  ssl: false
  host: influxdb.echo.local
  port: 80
  token: !secret inlfuxdb_token # manually assign in secrets.yaml
  bucket: ha-db0
  organization: aduh
  max_retries: 3
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
    entities:
      - weather.home

template:
  - sensor:
      - name: "Monitored Devices Unavailable"
        state: >
          {% set monitored_devices = states.device_tracker | selectattr('attributes.monitor', 'eq', true) %}
          {% set unavailable_devices = monitored_devices | selectattr('state', 'eq', 'unavailable') | list %}
          {{ unavailable_devices | length }}
        attributes:
          unavailable_devices: >
            {% set monitored_devices = states.device_tracker | selectattr('attributes.monitor', 'eq', true) %}
            {% set unavailable_devices = monitored_devices | selectattr('state', 'eq', 'unavailable') | list %}
            {{ unavailable_devices | map(attribute='entity_id') | list }}

wake_on_lan:

api:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
