
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.7.173      # Add the IP address of the proxy server
    - 172.21.0.0/16         # Traefik's Docker network address, Ip taken from logs
  ip_ban_enabled: true
  login_attempts_threshold: 3
# Text to speech
tts:
  - platform: google_translate


influxdb:
  api_version: 2
  ssl: false
  host: 192.168.7.173
  port: 8086
  token: <redacted>
  bucket: ha-db0
  organization: aduh
  max_retries: 3
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
    entities:
      - weather.home

wake_on_lan:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
