- HA:
    - Home Assistant:
        icon: si-homeassistant
        href: "https://hass.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Automations & dashboards

    - Zigbee2MQTT:
        icon: si-zigbee2mqtt
        href: "https://z2m.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Zigbee gateway

    - ESPHome:
        icon: si-esphome
        href: "https://esphome.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Device management

    - InfluxDB:
        icon: si-influxdb
        href: "https://influxdb.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Time-series DB

    - Grafana:
          icon: si-grafana
          href: "https://grafana.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
          description: Dashboards

- Media:
    - Immich:
        icon: si-immich
        href: "https://immich.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Photo library

    - Jellyfin:
        icon: si-jellyfin
        href: "https://jellyfin.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Media server

    - Radarr:
        icon: si-radarr
        href: "https://radarr.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Movie management

    - Sonarr:
        icon: si-sonarr
        href: "https://sonarr.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: TV management

    - qBittorrent:
        icon: si-qbittorrent
        href: "https://qb.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Torrent client

    - Prowlarr:
        icon: si-pagseguro
        href: "https://prowlarr.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Indexer manager

    - Bazarr:
        icon: si-sublimetext
        href: "https://bazarr.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Subtitle management

- Utils:
    - Opencloud:
        icon: si-googlecloud
        href: "https://opencloud.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Personal Cloud

    - Dockhand:
        icon: si-docker
        href: "https://dockhand.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Docker UI

    - Portainer:
        icon: si-portainer
        href: "https://portainer.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Container management

    - FileBrowser:
        icon: si-files
        href: "https://files.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: File manager

    - Semaphore:
        icon: si-ansible
        href: "https://semaphore.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Task automation

    - Uptime Kuma:
        icon: si-uptimekuma
        href: "https://uptime.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Status monitoring

    - n8n:
        icon: si-n8n
        href: "https://n8n.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Workflow automation

- Backup:
    - Backrest:
        icon: si-databricks
        href: "https://backrest.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Backup orchestrator

    - Syncthing Src:
        icon: si-syncthing
        href: "https://syncthing-src.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Source sync

    - Syncthing NAS:
        icon: si-syncthing
        href: "https://syncthing-nas.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: NAS sync

    - Syncthing Storage:
        icon: si-syncthing
        href: "https://syncthing-storage.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Storage sync

- Infra:
    - Wireguard:
        icon: si-wireguard
        href: "https://wg.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: VPN

    - Adguard Home:
        icon: si-adguard
        href: "https://adguard.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: DNS sinkhole

    - Traefik:
        icon: si-traefikproxy
        href: "https://traefik.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Edge router

    - Authentik:
        icon: si-authentik
        href: "https://authentik.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
        description: Identity provider



