title: Homelab

theme: dark
color: slate

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

layout:
  - Utils:
      style: row
      columns: 5
  - Infra:
      style: row
      columns: 5
  - Other:
      style: row
      columns: 4


providers:
  openweathermap: null

favicon: https://raw.githubusercontent.com/NX211/homer-icons/master/png/hubitat.png
#headerStyle: clean

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo