- greeting:
    text_size: xl

- datetime:
    locale: ro-RO
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23

- resources:
    cpu: true
    memory: true
    disk: ["/"]

- openmeteo:
    label: "Now"
    latitude: 44.43
    longitude: 26.10
    timezone: Europe/Bucharest
    units: metric
