#!/bin/bash

### MUST BE COPIED in .xinitrc file in home folder

xset s off
xset -dpms
xset s noblank

unclutter -idle 0.1 -root &

openbox-session &

# Start screensaver monitor
/home/pi/screensaver-watch.sh &

# MUST BE THE LAST COMMAND
# Launch your main Home Assistant kiosk page
chromium-browser --noerrdialogs --disable-infobars --kiosk http://hass.echo.local

