---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.8.2
    ports:
      - "8123:8123"
    volumes:
#      - $BASE_DIR/configs/ha:/config
      - ha-data:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.hass.rule=Host(`hass.${DOMAIN_NAME}`)"
      - "traefik.http.routers.hass.entrypoints=web"
      - "traefik.http.routers.hass.tls=false"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
     - "8086:8086"
    volumes:
      - influxdb2-config:/etc/influxdb2
      - influxdb2-data:/var/lib/influxdb2
    security_opt:
      - no-new-privileges:true
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.${DOMAIN_NAME}`)"
      - "traefik.http.routers.influxdb.entrypoints=web"
      - "traefik.http.routers.influxdb.tls=false"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
      - "9001:9001"  # Optional WebSocket
    volumes:
        # replace with configs
#      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.mosquitto.rule=Host(`mosquitto.${DOMAIN_NAME}`)"
      - "traefik.http.routers.mosquitto.entrypoints=web"
      - "traefik.http.routers.mosquitto.tls=false"
      - "traefik.http.services.mosquitto.loadbalancer.server.port=1883"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

#  esphome:
#    container_name: esphome
#    image: esphome/esphome:2025.7.5
#    restart: always
#    ports:
#      - 6052:6052
#    environment:
#      - TZ=Europe/Bucharest
#    volumes:
#      - $BASE_DIR/configs/esphome:/config
#    privileged: true
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#    labels:
#      - "portainer.io/managed=true"
#      - "io.portainer.accesscontrol.users=admin"
#      - "traefik.enable=true"
#      - "traefik.http.routers.esphome.rule=Host(`esphome.${DOMAIN_NAME}`)"
#      - "traefik.http.routers.esphome.entrypoints=web"
#      - "traefik.http.routers.esphome.tls=false"
#      - "traefik.http.services.esphome-utils.loadbalancer.server.port=1883"
#    network_mode: host

volumes:
  ha-data: {}
  influxdb2-data: {}
  influxdb2-config: {}
  mosquitto-config: {}
  mosquitto-data: {}
  mosquitto-logs: {}

networks:
  hlcl:
    name: hlcl
    external: true