{
 "title": "Aduh Rpi Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "Hardware temperature",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DIsk Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/\"} / (8*1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "title": "Throttle cooling device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_cooling_device_cur_state",
     "legendFormat": "Current {{ name }} in {{ type }}"
    },
    {
     "expr": "node_cooling_device_max_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max {{ name }} in {{ type }}"
    }
   ]
  },
  {
   "title": "Home Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Home Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "temperature_lumi_158d000391d212"
      }
     ]
    },
    {
     "alias": "Living",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "temperature_lumi_158d0003cb2d31"
      }
     ]
    },
    {
     "alias": "Balcony",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "temperature_lumi_158d0003cb89ed"
      }
     ]
    }
   ]
  },
  {
   "title": "Home Humids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "humidity_lumi_158d000391d212" }
     ]
    },
    {
     "alias": "Living",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "humidity_lumi_158d0003cb2d31" }
     ]
    },
    {
     "alias": "Balcony",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE (\"entity_id\"::tag = 'humidity_lumi_158d0003cb2d31') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "humidity_lumi_158d0003cb89ed" }
     ]
    }
   ]
  }
 ]
}