---
services:

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:11.5.8
    user: ${UID}
    security_opt:
      - no-new-privileges:true
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.tls=false"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

  alloy:
    container_name: alloy
    image: grafana/alloy:v1.10.1
    hostname: echo
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      #replace with configs
#      - $BASE_DIR/configs/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.alloy.rule=Host(`alloy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.alloy.entrypoints=web"
      - "traefik.http.routers.alloy.tls=false"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

  loki:
    container_name: loki
    image: grafana/loki:3.5.3
    command: "-config.file=/etc/loki/config.yaml"
    user: ${UID}
    ports:
      - "3100:3100"
    volumes:
      - $BASE_DIR/configs/loki/config.yaml:/etc/loki/config.yaml:ro
      - $BASE_DIR/data/loki:/loki:rw
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.${DOMAIN_NAME}`)"
      - "traefik.http.routers.loki.entrypoints=web"
      - "traefik.http.routers.loki.tls=false"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
       - hlcl

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.5.0
    user: root
    volumes:
        # replace with configs
#      - $BASE_DIR/configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=401d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    labels:
      - "portainer.io/managed=true"
      - "io.portainer.accesscontrol.users=admin"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.routers.prometheus.tls=false"
    restart: always
    deploy:
      update_config:
        order: start-first
    networks:
      - hlcl

volumes:
  grafana-data: {}
  alloy-data: {}
  prometheus-data: {}

networks:
  hlcl:
    name: hlcl
    external: true